version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build(deps)"
          include: "scope"

    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build(deps)"
          include: "scope"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build(deps)"
          include: "scope"
