name: Main
on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.20"
                  cache: false
            - name: Build
              run: "go build ./..."
            - name: Test
              run: "go test ./..."
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.20"
                  cache: false
            - name: Lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.53
                  args: --config=.golangci.yaml
